all: FindDevices NewAddress

FindDevices             :FindDevices.cpp ../iarduino_I2C_Keyboard.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Keyboard.cpp
getAllKeyState          :getAllKeyState.cpp ../iarduino_I2C_Keyboard.cpp
getKeyState             :getKeyState.cpp ../iarduino_I2C_Keyboard.cpp
getTime                 :getTime.cpp ../iarduino_I2C_Keyboard.cpp
printChar               :printChar.cpp ../iarduino_I2C_Keyboard.cpp
printString             :printString.cpp ../iarduino_I2C_Keyboard.cpp
setAllLed_KeyState      :setAllLed_KeyState.cpp ../iarduino_I2C_Keyboard.cpp
setAnimation            :setAnimation.cpp ../iarduino_I2C_Keyboard.cpp
setLed                  :setLed.cpp ../iarduino_I2C_Keyboard.cpp
setLed_KeyState         :setLed_KeyState.cpp ../iarduino_I2C_Keyboard.cpp
setLight                :setLight.cpp ../iarduino_I2C_Keyboard.cpp
setSettings             :setSettings.cpp ../iarduino_I2C_Keyboard.cpp

clean:
	rm -f FindDevices NewAddress getAllKeyState getKeyState getTime printChar printString setAllLed_KeyState setAnimation setLed setLed_KeyState setLight setSettings
