all: FindDevices NewAddress

FindDevices             :FindDevices.cpp ../iarduino_I2C_Keyboard.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Keyboard.cpp
getAllKeyState          :getAllKeyState.cpp ../iarduino_I2C_Keyboard.cpp

clean:
	rm -f FindDevices NewAddress getAllKeyState
